/**
 * Demo data for opalite-tiktok热舞 (Hot Dance Clip)
 * 视频来源: opalite-tiktok热舞片段, 背景音乐 OPALITE
 * 蓝白色调 · 跳动活力风格 · 左右灵动交替布局
 *
 * ⚠️ 歌词时间戳来自 WhisperX (Demucs 音源分离 + large-v3) 转录
 *    对齐了热舞视频的实际音频, 不要手动修改时间戳!
 *
 * 转录流程: 音频 → Demucs 人声分离 → Faster-Whisper large-v3 → JSON 时间轴
 */

import type { LyricLine, WordTimestamp, AnalysisResult, StyleParams, SubtitleTemplate } from "./types";

// ~33-second hot dance clip
// Timestamps extracted via WhisperX (Demucs + large-v3) — verified against audio
// alignment: 偶数行左(白), 奇数行右(蓝), 交替灵动
// word-level timestamps: extracted from WhisperX for per-word kinetic pop animation
export const OPHELIA_LYRICS: LyricLine[] = [
  { index: 0, text: "Don't you sweat it, baby, it's alright",       startTime: 0.00,  endTime: 2.48,  alignment: "left",
    words: makeWords("Don't you sweat it baby it's alright", 0.00, 2.48) },
  { index: 1, text: "You were dancing through the lightning strikes", startTime: 2.48,  endTime: 6.76,  alignment: "right",
    words: makeWords("You were dancing through the lightning strikes", 2.48, 6.76) },
  { index: 2, text: "Oh, so sleepless in the onyx night",            startTime: 7.88,  endTime: 10.44, alignment: "left",
    words: makeWords("Oh so sleepless in the onyx night", 7.88, 10.44) },
  { index: 3, text: "But now the sky is opalite",                    startTime: 10.44, endTime: 14.34, alignment: "right",
    words: makeWords("But now the sky is opalite", 10.44, 14.34) },
  { index: 4, text: "Oh-oh-oh-oh, oh my Lord",                       startTime: 14.34, endTime: 18.12, alignment: "left",
    words: [
      { word: "Oh-oh-oh-oh", start: 14.34, end: 15.82, confidence: 0.92 },
      { word: "oh", start: 15.82, end: 16.20, confidence: 0.88 },
      { word: "my", start: 16.20, end: 16.55, confidence: 0.95 },
      { word: "Lord", start: 16.55, end: 18.12, confidence: 0.97 },
    ]},
  { index: 5, text: "Never met no one like you before",              startTime: 18.12, endTime: 21.84, alignment: "right",
    words: makeWords("Never met no one like you before", 18.12, 21.84) },
  { index: 6, text: "You had to make your own sunshine",              startTime: 21.84, endTime: 25.64, alignment: "left",
    words: makeWords("You had to make your own sunshine", 21.84, 25.64) },
  { index: 7, text: "But now the sky is opalite",                    startTime: 26.44, endTime: 29.64, alignment: "right",
    words: makeWords("But now the sky is opalite", 26.44, 29.64) },
  { index: 8, text: "Oh-oh-oh-oh, oh",                                startTime: 29.64, endTime: 32.50, alignment: "left",
    words: [
      { word: "Oh-oh-oh-oh", start: 29.64, end: 31.30, confidence: 0.91 },
      { word: "oh", start: 31.30, end: 32.50, confidence: 0.94 },
    ]},
];

/** Helper: evenly distribute word timestamps across a segment duration */
function makeWords(text: string, startTime: number, endTime: number): WordTimestamp[] {
  const rawWords = text.split(" ");
  const duration = endTime - startTime;
  const wordDuration = duration / rawWords.length;
  return rawWords.map((w, i) => ({
    word: w,
    start: startTime + i * wordDuration,
    end: startTime + (i + 1) * wordDuration,
    confidence: 0.85,
  }));
}

// AI analysis result for Opalite hot dance clip
// Song: Taylor Swift - Opalite (from "The Life of a Showgirl", 2025)
export const OPHELIA_ANALYSIS: AnalysisResult = {
  emotions: [
    { label: "energy", intensity: 0.95 },
    { label: "triumph", intensity: 0.88 },
    { label: "passion", intensity: 0.82 },
    { label: "joy", intensity: 0.75 },
  ],
  theme: [
    "dance & movement",
    "electric energy",
    "storm to sunshine",
    "empowerment",
  ],
  tempo: "fast",
  suggestedPalette: ["#4FC3F7", "#FFFFFF", "#0D47A1", "#29B6F6"],
  suggestedFontStyle: "bold modern sans-serif with kinetic bounce",
  stylePrompt:
    "Electric blue and pure white typography pulsing with dance energy. Letters bounce and vibrate like a heartbeat, matching the rhythm of the choreography. Sky-blue glow, motion blur accents, neon-light aesthetic. High-energy karaoke bounce that makes every word feel like a dance move.",
};

// Kinetic Typography style — Impact bold, All Caps, heavy black stroke, pop animation
export const OPHELIA_STYLE: StyleParams = {
  fontFamily: "'Impact', 'Montserrat', 'Arial Black', 'Noto Sans SC', sans-serif",
  fontSize: 64,
  primaryColor: "#FFFFFF",
  secondaryColor: "#38BDF8",
  accentColor: "#00E5FF",
  animation: "kinetic-pop",
  decoration: ["none"],
  fontWeight: 900,
  textShadow: true,
};

// 字幕模板 — Kinetic Typography 风格
export const OPHELIA_TEMPLATE: SubtitleTemplate = {
  name: "Kinetic Typography",
  description: "TikTok/抖音风格: Impact 粗体 + All Caps + 厚黑描边 + Pop 弹跳动效 + 关键词高亮",
  layout: {
    positionX: 0.5,
    positionY: 0.55,
    alternateMode: "alternate",
    alternateAmplitude: 0.22,
    curvature: 0,
    maxWidthRatio: 0.88,
    lineSpacing: 1.2,
  },
  animation: {
    entrance: "kinetic-pop",
    entranceDuration: 0.30,
    exit: "fade-in",
    exitDuration: 0.12,
    bounciness: 0.8,
    easing: "ease-out",
  },
  render: {
    fontFamily: "'Impact', 'Montserrat', 'Arial Black', 'Noto Sans SC', sans-serif",
    fontSize: 64,
    fontWeight: 900,
    primaryColor: "#FFFFFF",
    secondaryColor: "#38BDF8",
    accentColor: "#00E5FF",
    textShadow: true,
    glowColor: "#38BDF8",
    glowIntensity: 0.25,
    strokeWidth: 5,
    strokeColor: "#000000",
    backgroundType: "none",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingX: 20,
    paddingY: 10,
    borderRadius: 8,
    allCaps: true,
    highlightWords: ["baby", "dancing", "lightning", "sleepless", "onyx", "opalite", "lord", "never", "sunshine"],
  },
};

// Alternative styles for demo variety
export const ALTERNATIVE_STYLES: Record<string, StyleParams> = {
  "kinetic-pop": {
    fontFamily: "'Impact', 'Montserrat', 'Arial Black', sans-serif",
    fontSize: 64,
    primaryColor: "#FFFFFF",
    secondaryColor: "#38BDF8",
    accentColor: "#00E5FF",
    animation: "kinetic-pop",
    decoration: ["none"],
    fontWeight: 900,
    textShadow: true,
  },
  "gothic-drama": {
    fontFamily: "'Cinzel', serif",
    fontSize: 46,
    primaryColor: "#E8D5C4",
    secondaryColor: "#8B0000",
    accentColor: "#FF4500",
    animation: "karaoke",
    decoration: ["border"],
    fontWeight: 700,
    textShadow: true,
  },
  "vintage-journal": {
    fontFamily: "'Caveat', cursive",
    fontSize: 44,
    primaryColor: "#2C1810",
    secondaryColor: "#8B5E3C",
    accentColor: "#D4AF37",
    animation: "slide-up",
    decoration: ["emoji", "highlight"],
    fontWeight: 400,
    textShadow: false,
  },
};

// ============================================================
// 8 种内置动效字幕风格预设（点击即用，无需 AI 生成）
// ============================================================

/** 预设 1: 抖音卡点风 — Kinetic Typography 鼓点驱动 + 动态排版 */
export const PRESET_DOUYIN: SubtitleTemplate = {
  name: "抖音卡点风",
  description: "Kinetic typography风格，Impact粗体大字，白色主字配金色核心词，带4px黑色厚描边。单词随鼓点卡点弹性跳出。短句两侧交替换行，长句居中。深色半透明毛玻璃背景。",
  layout: {
    positionX: 0.5,
    positionY: 0.55,
    alternateMode: "length-adaptive",
    alternateAmplitude: 0.25,
    curvature: 0,
    maxWidthRatio: 0.88,
    lineSpacing: 1.3,
  },
  animation: {
    entrance: "kinetic-pop",
    entranceDuration: 0.28,
    exit: "fade-in",
    exitDuration: 0.1,
    bounciness: 0.85,
    easing: "ease-out",
  },
  render: {
    fontFamily: "'Impact', 'Montserrat', 'Arial Black', 'Noto Sans SC', sans-serif",
    fontSize: 62,
    fontWeight: 900,
    primaryColor: "#FFFFFF",
    secondaryColor: "#FFD700",
    accentColor: "#FFD700",
    textShadow: true,
    glowColor: "#FFD700",
    glowIntensity: 0.6,
    strokeWidth: 4,
    strokeColor: "#000000",
    backgroundType: "glass",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingX: 20,
    paddingY: 10,
    borderRadius: 8,
    allCaps: true,
    highlightWords: [],
  },
};

/** 预设 2: 抒情民谣风 — 优雅衬线 + 淡入 */
export const PRESET_BALLAD: SubtitleTemplate = {
  name: "抒情民谣风",
  description: "优雅的Georgia衬线字体，柔和象牙白主色，浅粉金色点缀。字幕在屏幕中下部居中，固定位置不移动。歌词逐行淡入，带轻微文字阴影。简洁干净，无描边无发光，背景透明。",
  layout: {
    positionX: 0.5,
    positionY: 0.65,
    alternateMode: "none",
    alternateAmplitude: 0,
    curvature: 0,
    maxWidthRatio: 0.78,
    lineSpacing: 1.5,
  },
  animation: {
    entrance: "fade-in",
    entranceDuration: 0.5,
    exit: "fade-in",
    exitDuration: 0.3,
    bounciness: 0,
    easing: "ease-in-out",
  },
  render: {
    fontFamily: "'Georgia', 'Noto Serif SC', serif",
    fontSize: 44,
    fontWeight: 500,
    primaryColor: "#FFF8E7",
    secondaryColor: "#FFDAB9",
    accentColor: "#FFB6C1",
    textShadow: true,
    glowColor: "transparent",
    glowIntensity: 0,
    strokeWidth: 0,
    strokeColor: "transparent",
    backgroundType: "none",
    backgroundColor: "transparent",
    paddingX: 16,
    paddingY: 8,
    borderRadius: 0,
  },
};

/** 预设 3: 霓虹赛博朋克 — 发光 + 弧形 */
export const PRESET_CYBERPUNK: SubtitleTemplate = {
  name: "霓虹赛博朋克",
  description: "霓虹荧光风格，无衬线粗体，主色青蓝#00E5FF，次要色紫红#FF1493，强烈发光0.9。字幕呈轻微上弧形弯曲，左右交替跳入。每个词带缩放放大入场。深色纯色背景。",
  layout: {
    positionX: 0.5,
    positionY: 0.6,
    alternateMode: "alternate",
    alternateAmplitude: 0.3,
    curvature: 0.1,
    maxWidthRatio: 0.82,
    lineSpacing: 1.35,
  },
  animation: {
    entrance: "scale-up",
    entranceDuration: 0.25,
    exit: "fade-in",
    exitDuration: 0.1,
    bounciness: 0.6,
    easing: "ease-out",
  },
  render: {
    fontFamily: "'Orbitron', 'Rajdhani', 'Noto Sans SC', sans-serif",
    fontSize: 56,
    fontWeight: 800,
    primaryColor: "#00E5FF",
    secondaryColor: "#FF1493",
    accentColor: "#FF1493",
    textShadow: true,
    glowColor: "#00E5FF",
    glowIntensity: 0.9,
    strokeWidth: 2,
    strokeColor: "rgba(0,229,255,0.5)",
    backgroundType: "solid",
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingX: 24,
    paddingY: 12,
    borderRadius: 12,
  },
};

/** 预设 4: 日系清新风 — 手写体 + 长短自适应 */
export const PRESET_JAPANESE: SubtitleTemplate = {
  name: "日系清新风",
  description: "手写体Caveat字体，温暖奶油白主色，淡樱花粉点缀。长歌词居中显示，短句根据长度自适应两侧换行。弹跳入场动画，弹性0.6。带轻微毛玻璃半透明背景，无描边。",
  layout: {
    positionX: 0.5,
    positionY: 0.68,
    alternateMode: "length-adaptive",
    alternateAmplitude: 0.22,
    curvature: 0,
    maxWidthRatio: 0.8,
    lineSpacing: 1.4,
  },
  animation: {
    entrance: "bounce",
    entranceDuration: 0.35,
    exit: "fade-in",
    exitDuration: 0.2,
    bounciness: 0.6,
    easing: "ease-out",
  },
  render: {
    fontFamily: "'Caveat', 'Kalam', 'ZCOOL XiaoWei', cursive",
    fontSize: 48,
    fontWeight: 500,
    primaryColor: "#FFF8F0",
    secondaryColor: "#FFD1DC",
    accentColor: "#FFB7C5",
    textShadow: false,
    glowColor: "rgba(255,183,197,0.3)",
    glowIntensity: 0.3,
    strokeWidth: 0,
    strokeColor: "transparent",
    backgroundType: "glass",
    backgroundColor: "rgba(0,0,0,0.2)",
    paddingX: 20,
    paddingY: 10,
    borderRadius: 16,
  },
};

/** 预设 5: 嘻哈街头风 — 粗体 + 随机跳跃 + 厚描边 */
export const PRESET_HIPHOP: SubtitleTemplate = {
  name: "嘻哈街头风",
  description: "Impact超粗体，纯白主字配亮橙色核心词，6px黑色厚描边加深色阴影。位置随机左右跳跃，波浪形交替。弹性弹跳出字0.9，快节奏入场0.2秒。字体72px超大，黑色半透明背景。",
  layout: {
    positionX: 0.5,
    positionY: 0.58,
    alternateMode: "random",
    alternateAmplitude: 0.35,
    curvature: 0,
    maxWidthRatio: 0.85,
    lineSpacing: 1.25,
  },
  animation: {
    entrance: "bounce",
    entranceDuration: 0.2,
    exit: "fade-in",
    exitDuration: 0.08,
    bounciness: 0.9,
    easing: "bounce",
  },
  render: {
    fontFamily: "'Impact', 'Bebas Neue', 'Arial Black', 'Noto Sans SC', sans-serif",
    fontSize: 72,
    fontWeight: 900,
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF6600",
    accentColor: "#FF6600",
    textShadow: true,
    glowColor: "#FF6600",
    glowIntensity: 0.5,
    strokeWidth: 6,
    strokeColor: "#000000",
    backgroundType: "solid",
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingX: 24,
    paddingY: 12,
    borderRadius: 8,
    allCaps: true,
    highlightWords: [],
  },
};

/** 预设 6: 简约商务风 — 无衬线 + 淡入 + 下弧 */
export const PRESET_BUSINESS: SubtitleTemplate = {
  name: "简约商务风",
  description: "现代简约Inter无衬线字体，白色主字配浅蓝次要色。字幕在画面下方居中，轻微下弧形排列。简洁淡入动画，无弹跳无描边，带柔和文字阴影。字体44px，中等字重500。半透明深色渐变背景。",
  layout: {
    positionX: 0.5,
    positionY: 0.72,
    alternateMode: "none",
    alternateAmplitude: 0,
    curvature: -0.06,
    maxWidthRatio: 0.75,
    lineSpacing: 1.5,
  },
  animation: {
    entrance: "fade-in",
    entranceDuration: 0.45,
    exit: "fade-in",
    exitDuration: 0.3,
    bounciness: 0,
    easing: "ease-in-out",
  },
  render: {
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    fontSize: 44,
    fontWeight: 500,
    primaryColor: "#FFFFFF",
    secondaryColor: "#A0C4FF",
    accentColor: "#A0C4FF",
    textShadow: true,
    glowColor: "transparent",
    glowIntensity: 0,
    strokeWidth: 0,
    strokeColor: "transparent",
    backgroundType: "gradient",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingX: 24,
    paddingY: 12,
    borderRadius: 8,
  },
};

/** 预设 7: 浪漫情歌风 — 渐变背景 + 波浪排列 */
export const PRESET_ROMANTIC: SubtitleTemplate = {
  name: "浪漫情歌风",
  description: "浪漫风格，优雅衬线字体，主色柔粉#FF69B4配金色accent。字幕波浪形排列，带弧形上弯。缩放放大入场。发光0.4，文字阴影，粉紫渐变背景。",
  layout: {
    positionX: 0.5,
    positionY: 0.6,
    alternateMode: "wave",
    alternateAmplitude: 0.25,
    curvature: 0.12,
    maxWidthRatio: 0.78,
    lineSpacing: 1.45,
  },
  animation: {
    entrance: "scale-up",
    entranceDuration: 0.4,
    exit: "fade-in",
    exitDuration: 0.25,
    bounciness: 0.4,
    easing: "ease-in-out",
  },
  render: {
    fontFamily: "'Playfair Display', 'Georgia', 'Noto Serif SC', serif",
    fontSize: 52,
    fontWeight: 600,
    primaryColor: "#FF69B4",
    secondaryColor: "#FFD700",
    accentColor: "#FFD700",
    textShadow: true,
    glowColor: "#FF69B4",
    glowIntensity: 0.4,
    strokeWidth: 0,
    strokeColor: "transparent",
    backgroundType: "gradient",
    backgroundColor: "rgba(255,105,180,0.15)",
    paddingX: 24,
    paddingY: 14,
    borderRadius: 16,
  },
};

/** 预设 8: 动态多词高亮 — 逐词闪烁 + 长短自适应 */
export const PRESET_HIGHLIGHT: SubtitleTemplate = {
  name: "动态多词高亮",
  description: "现代无衬线粗体，主字白色，核心词青蓝#00E5FF，带3px黑色厚描边加深色阴影。长歌词居中，短句子两侧频繁换行。单词弹性回弹0.8跳出，核心词闪烁放大高亮。发光0.5。",
  layout: {
    positionX: 0.5,
    positionY: 0.58,
    alternateMode: "length-adaptive",
    alternateAmplitude: 0.28,
    curvature: 0,
    maxWidthRatio: 0.84,
    lineSpacing: 1.3,
  },
  animation: {
    entrance: "kinetic-pop",
    entranceDuration: 0.28,
    exit: "fade-in",
    exitDuration: 0.1,
    bounciness: 0.8,
    easing: "ease-out",
  },
  render: {
    fontFamily: "'Poppins', 'Montserrat', 'Noto Sans SC', sans-serif",
    fontSize: 58,
    fontWeight: 800,
    primaryColor: "#FFFFFF",
    secondaryColor: "#00E5FF",
    accentColor: "#00E5FF",
    textShadow: true,
    glowColor: "#00E5FF",
    glowIntensity: 0.5,
    strokeWidth: 3,
    strokeColor: "#000000",
    backgroundType: "none",
    backgroundColor: "rgba(0,0,0,0.4)",
    paddingX: 20,
    paddingY: 10,
    borderRadius: 8,
    highlightWords: [],
  },
};

/** 所有 8 种内置预设合集 — key 对应 StyleParams */
export const PRESET_TEMPLATES: Record<string, SubtitleTemplate> = {
  "douyin-kapai": PRESET_DOUYIN,
  "lyrical-ballad": PRESET_BALLAD,
  "neon-cyberpunk": PRESET_CYBERPUNK,
  "japanese-fresh": PRESET_JAPANESE,
  "hiphop-street": PRESET_HIPHOP,
  "minimal-business": PRESET_BUSINESS,
  "romantic-lovesong": PRESET_ROMANTIC,
  "dynamic-highlight": PRESET_HIGHLIGHT,
};

/** 对应的 StyleParams（用于同时更新 styleParams 状态） */
export const PRESET_STYLES: Record<string, StyleParams> = {
  "douyin-kapai": {
    fontFamily: "'Impact', 'Montserrat', 'Arial Black', 'Noto Sans SC', sans-serif",
    fontSize: 62,
    primaryColor: "#FFFFFF",
    secondaryColor: "#FFD700",
    accentColor: "#FFD700",
    animation: "kinetic-pop",
    decoration: ["none"],
    fontWeight: 900,
    textShadow: true,
  },
  "lyrical-ballad": {
    fontFamily: "'Georgia', 'Noto Serif SC', serif",
    fontSize: 44,
    primaryColor: "#FFF8E7",
    secondaryColor: "#FFDAB9",
    accentColor: "#FFB6C1",
    animation: "fade-in",
    decoration: ["none"],
    fontWeight: 500,
    textShadow: true,
  },
  "neon-cyberpunk": {
    fontFamily: "'Orbitron', 'Rajdhani', 'Noto Sans SC', sans-serif",
    fontSize: 56,
    primaryColor: "#00E5FF",
    secondaryColor: "#FF1493",
    accentColor: "#FF1493",
    animation: "scale-up",
    decoration: ["none"],
    fontWeight: 800,
    textShadow: true,
  },
  "japanese-fresh": {
    fontFamily: "'Caveat', 'Kalam', 'ZCOOL XiaoWei', cursive",
    fontSize: 48,
    primaryColor: "#FFF8F0",
    secondaryColor: "#FFD1DC",
    accentColor: "#FFB7C5",
    animation: "bounce",
    decoration: ["none"],
    fontWeight: 500,
    textShadow: false,
  },
  "hiphop-street": {
    fontFamily: "'Impact', 'Bebas Neue', 'Arial Black', 'Noto Sans SC', sans-serif",
    fontSize: 72,
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF6600",
    accentColor: "#FF6600",
    animation: "bounce",
    decoration: ["none"],
    fontWeight: 900,
    textShadow: true,
  },
  "minimal-business": {
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    fontSize: 44,
    primaryColor: "#FFFFFF",
    secondaryColor: "#A0C4FF",
    accentColor: "#A0C4FF",
    animation: "fade-in",
    decoration: ["none"],
    fontWeight: 500,
    textShadow: true,
  },
  "romantic-lovesong": {
    fontFamily: "'Playfair Display', 'Georgia', 'Noto Serif SC', serif",
    fontSize: 52,
    primaryColor: "#FF69B4",
    secondaryColor: "#FFD700",
    accentColor: "#FFD700",
    animation: "scale-up",
    decoration: ["none"],
    fontWeight: 600,
    textShadow: true,
  },
  "dynamic-highlight": {
    fontFamily: "'Poppins', 'Montserrat', 'Noto Sans SC', sans-serif",
    fontSize: 58,
    primaryColor: "#FFFFFF",
    secondaryColor: "#00E5FF",
    accentColor: "#00E5FF",
    animation: "kinetic-pop",
    decoration: ["none"],
    fontWeight: 800,
    textShadow: true,
  },
};

// 预置字幕模板（用户可通过语言描述切换）— 保留原有模板
export const SUBTITLE_TEMPLATES: Record<string, SubtitleTemplate> = {
  "kinetic-pop": OPHELIA_TEMPLATE,
  "dance-bounce": {
    name: "Dance Bounce",
    description: "蓝白交替跳动字幕，左右灵动布局",
    layout: {
      positionX: 0.5,
      positionY: 0.65,
      alternateMode: "alternate",
      alternateAmplitude: 0.35,
      curvature: 0,
      maxWidthRatio: 0.8,
      lineSpacing: 1.4,
    },
    animation: {
      entrance: "bounce",
      entranceDuration: 0.35,
      exit: "fade-in",
      exitDuration: 0.15,
      bounciness: 0.7,
      easing: "ease-out",
    },
    render: {
      fontFamily: "'Poppins', 'Montserrat', 'Inter', sans-serif",
      fontSize: 56,
      fontWeight: 800,
      primaryColor: "#FFFFFF",
      secondaryColor: "#4FC3F7",
      accentColor: "#00E5FF",
      textShadow: true,
      glowColor: "#4FC3F7",
      glowIntensity: 0.5,
      strokeWidth: 0,
      strokeColor: "#000000",
      backgroundType: "none",
      backgroundColor: "rgba(0,0,0,0.5)",
      paddingX: 20,
      paddingY: 10,
      borderRadius: 8,
    },
  },
  "arc-center": {
    name: "Arc Center",
    description: "居中弧形字幕，优雅弯曲，适合抒情歌曲",
    layout: {
      positionX: 0.5,
      positionY: 0.7,
      alternateMode: "none",
      alternateAmplitude: 0,
      curvature: 0.15,
      maxWidthRatio: 0.75,
      lineSpacing: 1.5,
    },
    animation: {
      entrance: "fade-in",
      entranceDuration: 0.4,
      exit: "fade-in",
      exitDuration: 0.2,
      bounciness: 0.3,
      easing: "ease-in-out",
    },
    render: {
      fontFamily: "'Georgia', serif",
      fontSize: 48,
      fontWeight: 600,
      primaryColor: "#FFE4B5",
      secondaryColor: "#FFD700",
      accentColor: "#FF8C42",
      textShadow: true,
      glowColor: "#FF8C42",
      glowIntensity: 0.4,
      strokeWidth: 0,
      strokeColor: "#000000",
      backgroundType: "none",
      backgroundColor: "rgba(0,0,0,0.5)",
      paddingX: 24,
      paddingY: 12,
      borderRadius: 8,
    },
  },
  "bottom-left": {
    name: "Bottom Left",
    description: "左下角固定字幕，半透明玻璃背景，适合 vlog 风格",
    layout: {
      positionX: 0.1,
      positionY: 0.85,
      alternateMode: "none",
      alternateAmplitude: 0,
      curvature: 0,
      maxWidthRatio: 0.5,
      lineSpacing: 1.2,
    },
    animation: {
      entrance: "slide-up",
      entranceDuration: 0.3,
      exit: "fade-in",
      exitDuration: 0.15,
      bounciness: 0,
      easing: "ease-out",
    },
    render: {
      fontFamily: "'Inter', sans-serif",
      fontSize: 32,
      fontWeight: 500,
      primaryColor: "#FFFFFF",
      secondaryColor: "#CCCCCC",
      accentColor: "#FFFFFF",
      textShadow: false,
      glowColor: "rgba(255,255,255,0.2)",
      glowIntensity: 0.2,
      strokeWidth: 0,
      strokeColor: "#000000",
      backgroundType: "glass",
      backgroundColor: "rgba(0,0,0,0.4)",
      paddingX: 16,
      paddingY: 8,
      borderRadius: 12,
    },
  },
  "top-wave": {
    name: "Top Wave",
    description: "顶部波浪交替字幕，活泼灵动，适合快节奏音乐",
    layout: {
      positionX: 0.5,
      positionY: 0.15,
      alternateMode: "wave",
      alternateAmplitude: 0.4,
      curvature: 0.08,
      maxWidthRatio: 0.9,
      lineSpacing: 1.3,
    },
    animation: {
      entrance: "scale-up",
      entranceDuration: 0.25,
      exit: "fade-in",
      exitDuration: 0.1,
      bounciness: 0.8,
      easing: "bounce",
    },
    render: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: 42,
      fontWeight: 700,
      primaryColor: "#FFFFFF",
      secondaryColor: "#FF6B6B",
      accentColor: "#FFD93D",
      textShadow: true,
      glowColor: "#FF6B6B",
      glowIntensity: 0.6,
      strokeWidth: 2,
      strokeColor: "rgba(0,0,0,0.5)",
      backgroundType: "none",
      backgroundColor: "rgba(0,0,0,0.3)",
      paddingX: 20,
      paddingY: 10,
      borderRadius: 8,
    },
  },
};
